org.gradle.jvmargs=-Xmx4G

java_version=21

minecraft_version=1.21.4

group=net.wiredtomato
mod_id=burgered
mod_name=Burgered
mod_description=Burgers Like Never Before
mod_author=WiredTomato
mod_version=0.2.0-beta.1

license=MIT

fabric_loader_version=0.16.9
fabric_version=0.114.3+1.21.4
flk_version=1.13.0+kotlin.2.1.0
mod_menu_version=13.0.0

neoforge_version=21.4.59-beta
kff_loader_version_range=[5,)
kff_version=5.7.0
minecraft_version_range=[1.21,)
credits=

cloth_config_version=17.0.144

neo_form_version=1.21.4-20241203.161809
parchment_minecraft=1.21.4
parchment_version=2025.01.05

kotlin.code.style=official
